### ISSUE TITLE
Fix duplicate faces

### ISSUE THREAD

**Issue by baz606** [Abid357/nostagalia#1]
The problem is in this line:
https://github.com/Abid357/nostagalia/blob/04fa777ec86426a011bfc1499f83d4fdde730b86/script.js#L261

allOptions array is referencing the original data.options array after you do a shuffle so each time we answer a question, the previous answer gets removed from the original array.

I added console.log(allOptions) line after line 260 and console.log(options) after line 262.
This is what I got:

<img width="399" alt="debug" src="https://github.com/Abid357/nostagalia/assets/19494753/a555b159-5194-4d14-8557-3aa590bd40b8">

Even though the options array shows one person at the end, I think the optionsButtons array retains previous values so we still see all four faces even if some are duplicates. However, I tested that the previous faces are not clickable.

Anyway, I applied a fix by making a copy of the data.options array before the shuffle so the original does not get altered:
```
  let allOptions = [...data.options];
  allOptions = shuffle(allOptions);
```
I did some testing and it looks good now.

**Comment by Abid357** [comment]
@baz606 jazak Allahu khair boi this was the fix, tested it, nicu.
